### ISSUE TITLE
Userstory 13: compose.yaml og Dockerfile

### ISSUE THREAD

**Issue by sshine** [augustrs/RetroGamer#19]
Det skal kunne lade sig gøre at skrive `docker compose build` og `docker compose up`.

For at det lader sig gøre, skal I have en `compose.yaml` og en `Dockerfile`.

I kan benytte `Dockerfile` som blev brugt i de to første individuelle afleveringsopgaver.

Den er generisk for Java-projekter med Maven og bygger projektet i to faser (multi-stage builds).

En skabelon til compose.yaml uden MySQL-understøttelse:

```yaml
services:
  jeres-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties:ro
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/application.properties
```

Jeg kan se at jeres application.properties har en MySQL-opsætning. Ovenstående `volumes:` og `environment:`-sektioner tjener det formål, at man kan bygge en Docker-container som ikke indeholder jeres MySQL-authentication, men først indlæser den idet i starter containeren. Det tilføjer et lag af sikkerhed, så ens kodeord ikke bliver gemt i git.

Linjen `./src/main/resources/application.properties:/app/application.properties:ro` virker hvis man står i jeres projektmappe når man skriver `docker compose up`: I et realistisk scenario vil man også ønske at kunne starte sine containere selvom man ikke har kildekoden tilgængelig, og man vil måske derfor gerne skrive noget andet end `./src/...`, da den application.properties man kan forestille sig at bruge i produktion ligger i en bestemt mappe på ens server. Det er ikke så vigtigt for afleveringen.

I kan også tilføje en MySQL-container i compose.yaml, hvis I vil. Det er dog valgfrit.

## Delopgaver

- [x] Kopier Dockerfile ind
- [x] Lav compose.yaml
- [x] Tjek at `docker compose build` virker
- [x] Lav pull request og tilføj mig som reviewer
